const UPDATE_DATA_BY_ID = "UPDATE_DATA_BY_ID";
const UPDATE_DATA_BY_COORDINATES = "UPDATE_DATA_BY_COORDINATES";
const SET_DATA = "SET_DATA";
const SET_SELECTED_CIRCLE_ID = "SET_SELECTED_CIRCLE_ID";
const ADD_CIRCLE_REQUEST = "ADD_CIRCLE_REQUEST";
const DELETE_CIRCLE = "DELETE_CIRCLE";
const DELETE_CIRCLE_REQUEST = "DELETE_CIRCLE_REQUEST";

export const circlesConstants = {
  UPDATE_DATA_BY_ID,
  UPDATE_DATA_BY_COORDINATES,
  SET_DATA,
  SET_SELECTED_CIRCLE_ID,
  ADD_CIRCLE_REQUEST,
  DELETE_CIRCLE_REQUEST,
  DELETE_CIRCLE,
};
