const UPDATE_CIRCLE = "UPDATE_CIRCLE";
const SET_CIRCLES = "SET_CIRCLES";
const SET_SELECTED_CIRCLE_ID = "SET_SELECTED_CIRCLE_ID";
const ADD_CIRCLE_REQUEST = "ADD_CIRCLE_REQUEST";
const DELETE_CIRCLE = "DELETE_CIRCLE";
const DELETE_CIRCLE_REQUEST = "DELETE_CIRCLE_REQUEST";
const UPDATE_CIRCLE_REQUEST = "UPDATE_CIRCLE_REQUEST";
const FETCH_CIRCLES_AND_CATEGORIES = "FETCH_MAP_DATA_REQUEST";

export const circlesConstants = {
  UPDATE_CIRCLE,
  SET_CIRCLES,
  SET_SELECTED_CIRCLE_ID,
  ADD_CIRCLE_REQUEST,
  DELETE_CIRCLE_REQUEST,
  DELETE_CIRCLE,
  UPDATE_CIRCLE_REQUEST,
  FETCH_CIRCLES_AND_CATEGORIES,
};
