const SET_CATEGORIES_REQUEST = "SET_CATEGORIES_REQUEST";
const SET_CATEGORIES = "SET_CATEGORIES";
const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
const ADD_CATEGORY = "ADD_CATEGORY";
const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
const DELETE_CATEGORY = "DELETE_CATEGORY";

export const categoriesConstants = {
  SET_CATEGORIES_REQUEST,
  SET_CATEGORIES,
  ADD_CATEGORY_REQUEST,
  ADD_CATEGORY,
  DELETE_CATEGORY_REQUEST,
  DELETE_CATEGORY,
};
