const FETCH_MAP_DATA_REQUEST = "FETCH_MAP_DATA_REQUEST";
const SET_LOADING = "SET_LOADING";
const DISPLAY_CATEGORY_MODAL = "DISPLAY_CATEGORY_MODAL";
const SET_SIDEBAR_VISIBILITY = "SET_SIDEBAR_VISIBILITY";

export const appConstants = {
  FETCH_MAP_DATA_REQUEST,
  SET_LOADING,
  DISPLAY_CATEGORY_MODAL,
  SET_SIDEBAR_VISIBILITY,
};
