const SET_LOADING = "SET_LOADING";
const SET_UPDATED = "SET_UPDATED";
const DISPLAY_CATEGORY_MODAL = "DISPLAY_CATEGORY_MODAL";
const SET_SIDEBAR_VISIBILITY = "SET_SIDEBAR_VISIBILITY";

export const appConstants = {
  SET_LOADING,
  SET_UPDATED,
  DISPLAY_CATEGORY_MODAL,
  SET_SIDEBAR_VISIBILITY,
};
