export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const UPDATE_DATA = "UPDATE_DATA";
export const SET_DATA = "SET_DATA";
export const DELETE_CIRCLE = "DELETE_CIRCLE";
export const SET_SELECTED_CIRCLE_ID = "SET_SELECTED_CIRCLE_ID";
